---
repos:
  ## 1. Global check =========================================================

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language:
          python
          #exclude: ^(src/.*|tests/.*)$

      - id: end-of-file-fixer
        name: Fix End of Files
        entry: mixed-line-ending
        language:
          python
          #exclude: ^(src/.*|tests/.*)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        name: Prettier
        description: "Checks JavaScript/TypeScript/Flow/JSX/JSON/CSS/SCSS/
          Less/HTML/Vue/Angular/GraphQL/Markdown/YAML"
        entry: prettier --write --list-different --ignore-unknown
        language:
          node
          #exclude: ^(src/.*|tests/.*)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        name: Check Misspellings
        language: python
        description:
          It looks for a set of common misspellings
          #exclude: ^(src/.*|tests/.*)$

  ## 2. Per language check ===================================================

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: requirements-txt-fixer
        name: Fix requirements.txt
        language: python

      - id: check-yaml
        name: Fix yaml
        entry: check-yaml
        language: python

      - id: check-toml
        name: Fix toml
        language: python

      - id: check-shebang-scripts-are-executable
        name: Check that executables have shebangs
        description: ensures that (non-binary) executables have a shebang.
        entry: check-executables-have-shebangs
        types: [text, executable]
        language: python

  ## Python related ----------------------------------------------------------

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        description: Check compliance with Python docstring conventions.
        language: python
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
      - id: autopep8
        name: Autopep8 Python
        description: Formats Python code to conform to the PEP 8 style guide
        language: python
        args: [-i]

  ## C/C++ related -----------------------------------------------------------

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        name: Fix C, C++, Objective-C, Java
        entry: clang-format-hook
        description: Formats C, C++, Objective-C, and Java code
        types_or: [c, c++, c#, objective-c, java]
        language: python
        args:
          [--style=Google, -i, --no-diff]
          #exclude: ^(src/.*|tests/.*)$

      - id: cppcheck
        name: Find warnings/errors in C, C++, and Objective-C
        entry: cppcheck-hook
        description: Find warnings/errors in C, C++, and Objective-C code
        types_or: [c, c++, c#, objective-c]
        language: python
        args:
          [--check-config]
          #exclude: ^(src/.*|tests/.*)$

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
        name: Fix cmake
        args: [--in-place]
        language: python
        types: [cmake]

  ## 3. Lints ================================================================

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cpplint
        name: Find lints in C/C++
        entry: cpplint-hook
        description: Find warnings/errors in C/CPP code
        types_or: [c, c++, c#, objective-c, cuda]
        language: python
        args:
          [
            "--filter=-legal/copyright,
            -build/include_subdir,
            -build/c++11,
            -runtime/references,
            -build/include_order",
          ]
          #exclude: ^(src/.*|tests/.*)$

  - repo: local
    hooks:
      - id: pylint
        name: Find lints in Python
        entry: pylint
        language: python
        types: [python]
        require_serial: true
