#ifndef CONFIGURE_HPP_
#define CONFIGURE_HPP_

enum {
  // thermodynamics data
  NPHASE_LEGACY = 2,

  // air-parcle data
  //NVAPOR = 2,
  NCLOUD = 2,
  NCHEMISTRY = 0,
  NTRACER = 0,
  NTURBULENCE = 0,

  // n-body data
  NINT_PARTICLE_DATA = 0,
  NREAL_PARTICLE_DATA = 0
};

// Affine option (AFFINE or NOT_AFFINE)
#define NOT_AFFINE

// Cubed Sphere option (CUBED_SPHERE or NOT_CUBED_SPHERE)
#define NOT_CUBED_SPHERE

// NetCDF output (NETCDFOUTPUT or NO_NETCDFOUTPUT)
#define NETCDFOUTPUT

// PNetCDF output (PNETCDFOUTPUT or NO_PNETCDFOUTPUT)
#define PNETCDFOUTPUT

// FITS option (FITSOUTPUT or NOT_FITSOUTPUT)
#define NO_FITSOUTPUT

// HYDROSTATIC option (HYDROSTATIC or NOT_HYDROSTATIC)
#define NOT_HYDROSTATIC

// MPI parallelization (MPI_PARALLEL or NOT_MPI_PARALLEL)
#define MPI_PARALLEL

// DISORT option (RT_DISORT or NOT_RT_DISORT)
#define NOT_RT_DISORT

// PVFMM option (ENABLE_PVFMM or DISABLE_PVFMM)
#define DISABLE_PVFMM

// Google log option (ENABLE_GLOG or DISABLE_GLOG)
#define DISABLE_GLOG

// python bindings (PYTHON_BINDINGS or NO_PYTHOND_BINDINGS)
#define NO_PYTHON_BINDINGS

#endif  // CONFIGURE_HPP_
